<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1323597</bug_id>
          
          <creation_ts>2016-04-04 04:04:00 -0400</creation_ts>
          <short_desc>arandr - xrandr 1.5 support</short_desc>
          <delta_ts>2016-11-28 11:26:52 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>arandr</component>
          <version>24</version>
          <rep_platform>All</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>CURRENTRELEASE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>medium</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Michele Baldessari">michele</reporter>
          <assigned_to name="Maros Zatko">mzatko</assigned_to>
          <cc>mike</cc>
    
    
    <cc>mvanross</cc>
    
    
    <cc>mzatko</cc>
    
    
    <cc>thrcka</cc>
    
    
    <cc>zapster</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>Bug Fix</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-11-28 11:26:52</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9203588</commentid>
    <comment_count>0</comment_count>
    <who name="Michele Baldessari">michele</who>
    <bug_when>2016-04-04 04:04:40 -0400</bug_when>
    <thetext>Description of problem:
Moved to f24 and got the following backtrace:


Traceback (most recent call last):
  File &quot;/usr/bin/arandr&quot;, line 42, in &lt;module&gt;
    main()
  File &quot;/usr/lib/python2.7/site-packages/screenlayout/gui.py&quot;, line 318, in main
    force_version=options.force_version
  File &quot;/usr/lib/python2.7/site-packages/screenlayout/gui.py&quot;, line 157, in __init__
    self.widget = widget.ARandRWidget(display=randr_display, force_version=force_version)
  File &quot;/usr/lib/python2.7/site-packages/screenlayout/widget.py&quot;, line 48, in __init__
    self._xrandr = XRandR(display=display, force_version=force_version)
  File &quot;/usr/lib/python2.7/site-packages/screenlayout/xrandr.py&quot;, line 42, in __init__
    raise Exception(&quot;XRandR 1.2/1.3 required.&quot;)
Exception: XRandR 1.2/1.3 required.



Version-Release number of selected component (if applicable):
arandr-0.1.7.1-6.fc24.noarch

This is due to xrandr being 1.5 now:
randr -v    
xrandr program version       1.5.0
Server reports RandR version 1.5


Adding the version in /usr/lib/python2.7/site-packages/screenlayout/xrandr.py
fixes things for me.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9294698</commentid>
    <comment_count>1</comment_count>
    <who name="Mark van Rossum">mvanross</who>
    <bug_when>2016-05-05 04:10:59 -0400</bug_when>
    <thetext>Or run with 
 arandr   --force-version</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9404368</commentid>
    <comment_count>2</comment_count>
    <who name="Mike Gerber">mike</who>
    <bug_when>2016-06-10 10:58:44 -0400</bug_when>
    <thetext>A simple update to arandr 0.1.9 (see BZ#1316257) fixed this for me.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9930332</commentid>
    <comment_count>3</comment_count>
    <who name="Mike Gerber">mike</who>
    <bug_when>2016-11-25 10:46:12 -0500</bug_when>
    <thetext>Dear maintainer,

arandr 0.1.9 is now in in Fedora (F23-F25), so I think this bug can be closed.

https://apps.fedoraproject.org/packages/arandr

Thanks,
Mike</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>