<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1365669</bug_id>
          
          <creation_ts>2016-08-09 15:45:00 -0400</creation_ts>
          <short_desc>The ipa-server-upgrade command failed when named-pkcs11 does not happen to run during dnf upgrade</short_desc>
          <delta_ts>2016-11-19 16:01:20 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>freeipa</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Regression, Reopened</keywords>
          <priority>unspecified</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1367022</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Jan Pazdziora">jpazdziora</reporter>
          <assigned_to name="Petr Spacek">pspacek</assigned_to>
          <cc>abokovoy</cc>
    
    
    <cc>ipa-maint</cc>
    
    
    <cc>jcholast</cc>
    
    
    <cc>jhrozek</cc>
    
    
    <cc>jpazdziora</cc>
    
    
    <cc>mbabinsk</cc>
    
    
    <cc>mbasti</cc>
    
    
    <cc>mkosek</cc>
    
    
    <cc>pspacek</cc>
    
    
    <cc>pvoborni</cc>
    
    
    <cc>rcritten</cc>
    
    
    <cc>ssorce</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>freeipa-4.3.2-2.fc24 freeipa-4.4.2-1.fc25</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-11-19 16:01:20</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9600386</commentid>
    <comment_count>0</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-08-09 15:45:28 -0400</bug_when>
    <thetext>Description of problem:

When freeipa-server-4.3.1-1.fc24.x86_64 gets upgraded to freeipa-server-4.3.2-1.fc24.x86_64 and named-pkcs11 service is not running in the posttrans (?), error

DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0009489059 seconds
Upgrade failed with The DNS operation timed out after 30.0009489059 seconds
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
(&apos;IPA upgrade failed.&apos;, 1)
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information

is shown.

Version-Release number of selected component (if applicable):

freeipa-server-4.3.2-1.fc24.x86_64

How reproducible:

Deterministic.

Steps to Reproduce:
1. Install Freeipa 4.3.1, configure it with ipa-server-install --setup-dns.
2. Run dnf upgrade --downloadonly --enablerepo updates-testing freeipa-server.
3. Run systemctl stop named-pkcs11
4. Run dnf upgrade --enablerepo updates-testing freeipa-server

Actual results:

  Upgrading   : freeipa-common-4.3.2-1.fc24.noarch           1/20 
  Upgrading   : freeipa-client-common-4.3.2-1.fc24.noarch    2/20 
  Upgrading   : freeipa-server-common-4.3.2-1.fc24.noarch    3/20 
  Upgrading   : python2-ipalib-4.3.2-1.fc24.noarch           4/20 
  Upgrading   : python2-ipaclient-4.3.2-1.fc24.noarch        5/20 
  Upgrading   : freeipa-client-4.3.2-1.fc24.x86_64           6/20 
Could not load host key: /etc/ssh/ssh_host_dsa_key
  Upgrading   : python2-ipaserver-4.3.2-1.fc24.noarch        7/20 
  Upgrading   : freeipa-admintools-4.3.2-1.fc24.noarch       8/20 
  Upgrading   : freeipa-server-4.3.2-1.fc24.x86_64           9/20 
  Upgrading   : freeipa-server-dns-4.3.2-1.fc24.noarch      10/20 
  Cleanup     : freeipa-server-dns-4.3.1-1.fc24.noarch      11/20 
  Cleanup     : freeipa-server-4.3.1-1.fc24.x86_64          12/20 
  Cleanup     : python2-ipaserver-4.3.1-1.fc24.noarch       13/20 
  Cleanup     : freeipa-client-4.3.1-1.fc24.x86_64          14/20 
  Cleanup     : python2-ipaclient-4.3.1-1.fc24.noarch       15/20 
  Cleanup     : freeipa-admintools-4.3.1-1.fc24.noarch      16/20 
  Cleanup     : python2-ipalib-4.3.1-1.fc24.noarch          17/20 
  Cleanup     : freeipa-server-common-4.3.1-1.fc24.noarch   18/20 
  Cleanup     : freeipa-client-common-4.3.1-1.fc24.noarch   19/20 
  Cleanup     : freeipa-common-4.3.1-1.fc24.noarch          20/20 
DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0009489059 seconds
Upgrade failed with The DNS operation timed out after 30.0009489059 seconds
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
(&apos;IPA upgrade failed.&apos;, 1)
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
  Verifying   : freeipa-server-4.3.2-1.fc24.x86_64           1/20 
  Verifying   : freeipa-admintools-4.3.2-1.fc24.noarch       2/20 

Expected results:

No error.

Additional info:

The /var/log/ipaupgrade.log ends with

2016-08-09T19:37:05Z DEBUG dnsconfig_show(rights=False, all=True, raw=False, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG Executing upgrade plugin: update_dnsforward_emptyzones
2016-08-09T19:37:05Z DEBUG raw: update_dnsforward_emptyzones
2016-08-09T19:37:05Z DEBUG raw: dnsconfig_show(all=True, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG dnsconfig_show(rights=False, all=True, raw=False, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG Updating forwarding policies in LDAP to avoid conflicts with automatic empty zones
2016-08-09T19:37:05Z DEBUG raw: dnsconfig_mod(ipadnsversion=2, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG dnsconfig_mod(ipadnsversion=2, rights=False, all=False, raw=False, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG raw: dnsforwardzone_find(None, all=True, raw=True, version=u&apos;2.164&apos;)
2016-08-09T19:37:05Z DEBUG dnsforwardzone_find(None, all=True, raw=True, version=u&apos;2.164&apos;, pkey_only=False)
2016-08-09T19:37:35Z ERROR DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0009489059 seconds
2016-08-09T19:37:35Z DEBUG Destroyed connection context.ldap2_140607877043344
2016-08-09T19:37:35Z ERROR Upgrade failed with The DNS operation timed out after 30.0009489059 seconds
2016-08-09T19:37:35Z DEBUG Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/upgradeinstance.py&quot;, line 216, in __upgrade
    self.modified = (ld.update(self.files) or self.modified)
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/ldapupdate.py&quot;, line 918, in update
    self._run_updates(all_updates)
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/ldapupdate.py&quot;, line 890, in _run_updates
    self._run_update_plugin(update[&apos;plugin&apos;])
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/ldapupdate.py&quot;, line 863, in _run_update_plugin
    restart_ds, updates = self.api.Updater[plugin_name]()
  File &quot;/usr/lib/python2.7/site-packages/ipalib/frontend.py&quot;, line 1404, in __call__
    return self.execute(**options)
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/plugins/dns.py&quot;, line 492, in execute
    if dnsutil.has_empty_zone_addresses(self.api.env.host):
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 278, in has_empty_zone_addresses
    ip_addresses = resolve_ip_addresses(hostname)
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 328, in resolve_ip_addresses
    rrsets = resolve_rrsets(fqdn, [&apos;A&apos;, &apos;AAAA&apos;])
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 305, in resolve_rrsets
    answer = dns.resolver.query(fqdn, rdtype)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 1029, in query
    raise_on_no_answer, source_port)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 949, in query
    timeout = self._compute_timeout(start)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 770, in _compute_timeout
    raise Timeout(timeout=duration)
Timeout: The DNS operation timed out after 30.0009489059 seconds

2016-08-09T19:37:35Z DEBUG Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/service.py&quot;, line 447, in start_creation
    run_step(full_msg, method)
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/service.py&quot;, line 437, in run_step
    method()
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/upgradeinstance.py&quot;, line 224, in __upgrade
    raise RuntimeError(e)
RuntimeError: The DNS operation timed out after 30.0009489059 seconds

2016-08-09T19:37:35Z DEBUG   [error] RuntimeError: The DNS operation timed out after 30.0009489059 seconds
2016-08-09T19:37:35Z DEBUG   [cleanup]: stopping directory server
2016-08-09T19:37:35Z DEBUG Starting external process
2016-08-09T19:37:35Z DEBUG args=/bin/systemctl stop dirsrv@EXAMPLE-TEST.service
2016-08-09T19:37:37Z DEBUG Process finished, return code=0
2016-08-09T19:37:37Z DEBUG stdout=
2016-08-09T19:37:37Z DEBUG stderr=
2016-08-09T19:37:37Z DEBUG   duration: 1 seconds
2016-08-09T19:37:37Z DEBUG   [cleanup]: restoring configuration
2016-08-09T19:37:37Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Saving StateFile to &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Saving StateFile to &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysrestore/sysrestore.state&apos;
2016-08-09T19:37:37Z DEBUG   duration: 0 seconds
2016-08-09T19:37:37Z ERROR IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
2016-08-09T19:37:37Z DEBUG   File &quot;/usr/lib/python2.7/site-packages/ipapython/admintool.py&quot;, line 171, in execute
    return_value = self.run()
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/ipa_server_upgrade.py&quot;, line 50, in run
    raise admintool.ScriptError(str(e))

2016-08-09T19:37:37Z DEBUG The ipa-server-upgrade command failed, exception: ScriptError: (&apos;IPA upgrade failed.&apos;, 1)
2016-08-09T19:37:37Z ERROR (&apos;IPA upgrade failed.&apos;, 1)
2016-08-09T19:37:37Z ERROR The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9600391</commentid>
    <comment_count>1</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-08-09 15:47:28 -0400</bug_when>
    <thetext>While this might seem like theoretical exercise, it actually happens in container installations where after running the container from new image, we need to run ipa-server-upgrade as soon as possible, before all the services are running. And indeed, new named with new DS might not even start before schema and everything is upgraded, so we cannot blindly start named-pkcs11.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9600445</commentid>
    <comment_count>2</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-08-09 16:11:01 -0400</bug_when>
    <thetext>This really is a regression -- previous versions of FreeIPA did not expect services to be in some state.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9606781</commentid>
    <comment_count>3</comment_count>
    <who name="Petr Spacek">pspacek</who>
    <bug_when>2016-08-11 07:44:54 -0400</bug_when>
    <thetext>Upstream ticket:
https://fedorahosted.org/freeipa/ticket/6205</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9618679</commentid>
    <comment_count>7</comment_count>
    <who name="Martin Bašti">mbasti</who>
    <bug_when>2016-08-16 08:26:05 -0400</bug_when>
    <thetext>Fixed upstream
master:
https://fedorahosted.org/freeipa/changeset/f2fe35721967531257bc952b766a7c77e71be826
ipa-4-3:
https://fedorahosted.org/freeipa/changeset/27534f8d7294536364147b18b76ecb2bac67870f</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9631048</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-08-19 11:59:15 -0400</bug_when>
    <thetext>freeipa-4.3.2-2.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2016-92a3655b70</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9632143</commentid>
    <comment_count>9</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-08-19 19:21:14 -0400</bug_when>
    <thetext>freeipa-4.3.2-2.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-92a3655b70</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9660563</commentid>
    <comment_count>10</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-08-29 14:53:55 -0400</bug_when>
    <thetext>freeipa-4.3.2-2.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9685589</commentid>
    <comment_count>11</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-09-07 04:30:35 -0400</bug_when>
    <thetext>Upgrading from 4.3.1-1.fc24 to 4.3.2-2.fc24 still complains:

  Upgrading   : freeipa-common-4.3.2-2.fc24.noarch                         1/20 
  Upgrading   : freeipa-client-common-4.3.2-2.fc24.noarch                  2/20 
  Upgrading   : freeipa-server-common-4.3.2-2.fc24.noarch                  3/20 
  Upgrading   : python2-ipalib-4.3.2-2.fc24.noarch                         4/20 
  Upgrading   : python2-ipaclient-4.3.2-2.fc24.noarch                      5/20 
  Upgrading   : freeipa-client-4.3.2-2.fc24.x86_64                         6/20 
Could not load host key: /etc/ssh/ssh_host_dsa_key
  Upgrading   : python2-ipaserver-4.3.2-2.fc24.noarch                      7/20 
  Upgrading   : freeipa-admintools-4.3.2-2.fc24.noarch                     8/20 
  Upgrading   : freeipa-server-4.3.2-2.fc24.x86_64                         9/20 
  Upgrading   : freeipa-server-dns-4.3.2-2.fc24.noarch                    10/20 
  Cleanup     : freeipa-server-dns-4.3.1-1.fc24.noarch                    11/20 
  Cleanup     : freeipa-server-4.3.1-1.fc24.x86_64                        12/20 
  Cleanup     : python2-ipaserver-4.3.1-1.fc24.noarch                     13/20 
  Cleanup     : freeipa-client-4.3.1-1.fc24.x86_64                        14/20 
  Cleanup     : python2-ipaclient-4.3.1-1.fc24.noarch                     15/20 
  Cleanup     : freeipa-admintools-4.3.1-1.fc24.noarch                    16/20 
  Cleanup     : python2-ipalib-4.3.1-1.fc24.noarch                        17/20 
  Cleanup     : freeipa-server-common-4.3.1-1.fc24.noarch                 18/20 
  Cleanup     : freeipa-client-common-4.3.1-1.fc24.noarch                 19/20 
  Cleanup     : freeipa-common-4.3.1-1.fc24.noarch                        20/20
MARK-LWD-LOOP -- 2016-09-07 04:15:09 --
 
DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0014810562 seconds
Skipping update of global DNS forwarder in LDAP: Unable to determine if local server is using an IP address belonging to an automatic empty zone. Consider changing forwarding policy to &quot;only&quot;. DNS exception: The DNS operation timed out after 30.0014810562 seconds
DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0013720989 seconds
IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
Unexpected error - see /var/log/ipaupgrade.log for details:
Timeout: The DNS operation timed out after 30.0013720989 seconds
The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
  Verifying   : freeipa-server-4.3.2-2.fc24.x86_64                         1/20 
  Verifying   : freeipa-admintools-4.3.2-2.fc24.noarch                     2/20 
  Verifying   : freeipa-client-4.3.2-2.fc24.x86_64                         3/20 
  Verifying   : freeipa-common-4.3.2-2.fc24.noarch                         4/20 

and the log shows

2016-09-07T08:16:44Z INFO [Checking global forwarding policy in named.conf to avoid conflicts with automatic empty zones]
2016-09-07T08:16:44Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysupgrade/sysupgrade.state&apos;
2016-09-07T08:16:44Z DEBUG Loading StateFile from &apos;/var/lib/ipa/sysupgrade/sysupgrade.state&apos;
2016-09-07T08:16:44Z DEBUG Saving StateFile to &apos;/var/lib/ipa/sysupgrade/sysupgrade.state&apos;
2016-09-07T08:17:14Z ERROR DNS query for ipa.example.test. A failed: The DNS operation timed out after 30.0013720989 seconds
2016-09-07T08:17:14Z ERROR IPA server upgrade failed: Inspect /var/log/ipaupgrade.log and run command ipa-server-upgrade manually.
2016-09-07T08:17:14Z DEBUG   File &quot;/usr/lib/python2.7/site-packages/ipapython/admintool.py&quot;, line 171, in execute
    return_value = self.run()
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/ipa_server_upgrade.py&quot;, line 48, in run
    server.upgrade()
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py&quot;, line 1781, in upgrade
    upgrade_configuration()
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py&quot;, line 1671, in upgrade_configuration
    named_update_global_forwarder_policy(),
  File &quot;/usr/lib/python2.7/site-packages/ipaserver/install/server/upgrade.py&quot;, line 817, in named_update_global_forwarder_policy
    if not dnsutil.has_empty_zone_addresses(api.env.host):
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 278, in has_empty_zone_addresses
    ip_addresses = resolve_ip_addresses(hostname)
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 328, in resolve_ip_addresses
    rrsets = resolve_rrsets(fqdn, [&apos;A&apos;, &apos;AAAA&apos;])
  File &quot;/usr/lib/python2.7/site-packages/ipapython/dnsutil.py&quot;, line 305, in resolve_rrsets
    answer = dns.resolver.query(fqdn, rdtype)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 1029, in query
    raise_on_no_answer, source_port)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 858, in query
    timeout = self._compute_timeout(start)
  File &quot;/usr/lib/python2.7/site-packages/dns/resolver.py&quot;, line 770, in _compute_timeout
    raise Timeout(timeout=duration)

2016-09-07T08:17:14Z DEBUG The ipa-server-upgrade command failed, exception: Timeout: The DNS operation timed out after 30.0013720989 seconds
2016-09-07T08:17:14Z ERROR Unexpected error - see /var/log/ipaupgrade.log for details:
Timeout: The DNS operation timed out after 30.0013720989 seconds
2016-09-07T08:17:14Z ERROR The ipa-server-upgrade command failed. See /var/log/ipaupgrade.log for more information
+ code=0</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9707193</commentid>
    <comment_count>13</comment_count>
    <who name="Martin Babinsky">mbabinsk</who>
    <bug_when>2016-09-14 08:57:50 -0400</bug_when>
    <thetext>Fixed upstream
ipa-4-3:
https://fedorahosted.org/freeipa/changeset/2d011b97c8a56d9eabae2ca3d88c30314e0adb58
https://fedorahosted.org/freeipa/changeset/93756dc719723bbec93497ecd6e06e325e6eecbd
ipa-4-4:
https://fedorahosted.org/freeipa/changeset/afeb4bd8a6039173c24201803f1253fae2529a83
https://fedorahosted.org/freeipa/changeset/e39cc53d90175e3cae6805302f318a96bc0e1af1
master:
https://fedorahosted.org/freeipa/changeset/22fd6f020940b5b2a1258f8e0e6058c95f7a1ba5
https://fedorahosted.org/freeipa/changeset/271a4f098230112ee0e3ea3ffb3a509977ee7330</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9793908</commentid>
    <comment_count>14</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-10-14 17:54:47 -0400</bug_when>
    <thetext>freeipa-4.4.2-1.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-d89b3f7913</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9905653</commentid>
    <comment_count>15</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-11-19 16:01:20 -0500</bug_when>
    <thetext>freeipa-4.4.2-1.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>