<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1365698</bug_id>
          
          <creation_ts>2016-08-09 19:47:00 -0400</creation_ts>
          <short_desc>python3-dnf-plugins-extras-tracer depends on python2-tracer (instead of python3-tracer)</short_desc>
          <delta_ts>2016-11-30 06:00:00 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>dnf-plugins-extras</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>RAWHIDE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Triaged</keywords>
          <priority>low</priority>
          <bug_severity>unspecified</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1340802</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Dominik &apos;Rathann&apos; Mierzejewski">dominik</reporter>
          <assigned_to>rpm-software-management</assigned_to>
          <cc>ignatenko</cc>
    
    
    <cc>jkadlcik</cc>
    
    
    <cc>jsilhan</cc>
    
    
    <cc>mluscon</cc>
    
    
    <cc>rpm-software-management</cc>
    
    
    <cc>vmukhame</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-11-30 06:00:00</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9600762</commentid>
    <comment_count>0</comment_count>
    <who name="Dominik &apos;Rathann&apos; Mierzejewski">dominik</who>
    <bug_when>2016-08-09 19:47:51 -0400</bug_when>
    <thetext>Description of problem:
python3-dnf-plugins-extras-tracer pulls in python2-tracer due to dependency on &quot;tracer&quot; instead of &quot;python3-tracer&quot;.

Version-Release number of selected component (if applicable):
0.0.12-1.fc23

How reproducible:
Always

Steps to Reproduce:
1. install python3-tracer
2. try removing python2-tracer

Actual results:
dnf wants to remove python3-dnf-plugins-extras-tracer as well.

Expected results:
python3-dnf-plugins-extras-tracer should not depend on python2-tracer</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9903169</commentid>
    <comment_count>1</comment_count>
    <who name="Dominik &apos;Rathann&apos; Mierzejewski">dominik</who>
    <bug_when>2016-11-18 07:15:15 -0500</bug_when>
    <thetext>Still valid on F24 (0.0.12-3.fc24.noarch). It&apos;s been 3 months and this seems like a very simple change, so if there&apos;s no action here for another week, I&apos;ll fix it myself.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9904327</commentid>
    <comment_count>2</comment_count>
    <who name="Igor Gnatenko">ignatenko</who>
    <bug_when>2016-11-18 13:23:01 -0500</bug_when>
    <thetext>(In reply to Dominik &apos;Rathann&apos; Mierzejewski from comment #1)
&gt; Still valid on F24 (0.0.12-3.fc24.noarch). It&apos;s been 3 months and this seems
&gt; like a very simple change, so if there&apos;s no action here for another week,
&gt; I&apos;ll fix it myself.
Unfortunately it&apos;s not trivial to do, in current version we run it through subprocess.

https://github.com/rpm-software-management/dnf-plugins-extras/commit/4a29b1eda1e12faf4a2b19e9ba030098086a21ea

I will try to backport this, but priority is to fix &amp; release dnf-plugins-extras for DNF 2.0</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>