<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1404194</bug_id>
          
          <creation_ts>2016-12-13 05:02:00 -0500</creation_ts>
          <short_desc>fedpkg new-sources complains about 302 to https://src.fedoraproject.org/repo/pkgs/upload.cgi</short_desc>
          <delta_ts>2017-03-02 07:07:18 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>fedpkg</component>
          <version>24</version>
          <rep_platform>Unspecified</rep_platform>
          <op_sys>Unspecified</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>CURRENTRELEASE</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords>Reopened</keywords>
          <priority>urgent</priority>
          <bug_severity>urgent</bug_severity>
          <target_milestone>---</target_milestone>
          
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Jan Pazdziora">jpazdziora</reporter>
          <assigned_to>cqi</assigned_to>
          <cc>anto.trande</cc>
    
    
    <cc>bochecha</cc>
    
    
    <cc>cqi</cc>
    
    
    <cc>dennis</cc>
    
    
    <cc>jpazdziora</cc>
    
    
    <cc>kvolny</cc>
    
    
    <cc>lsedlar</cc>
    
    
    <cc>mschorm</cc>
    
    
    <cc>pahan</cc>
    
    
    <cc>pbabinca</cc>
    
    
    <cc>s</cc>
    
    
    <cc>zsvetlik</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in></cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-03-02 07:07:18</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9980216</commentid>
    <comment_count>0</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-12-13 05:02:35 -0500</bug_when>
    <thetext>Description of problem:

On freshly installed fedpkg setup (with fresh /etc/rpkg/fedpkg.conf), attempt to run

   fedpkg new-sources name-version.tar.gz

fails with

Could not execute new_sources: &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;302 Found&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Found&lt;/h1&gt;
&lt;p&gt;The document has moved &lt;a href=&quot;https://src.fedoraproject.org/repo/pkgs/upload.cgi&quot;&gt;here&lt;/a&gt;.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;

Version-Release number of selected component (if applicable):

fedpkg-1.25-1.fc24.noarch

How reproducible:

Deterministic.

Steps to Reproduce:
1. Have some file around that you want to upload to the lookaside cache.
2. Run fedpkg new-sources name-version.tar.gz

Actual results:

Could not execute new_sources: &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;302 Found&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Found&lt;/h1&gt;
&lt;p&gt;The document has moved &lt;a href=&quot;https://src.fedoraproject.org/repo/pkgs/upload.cgi&quot;&gt;here&lt;/a&gt;.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;

Expected results:

No error.

Additional info:

If the code cannot or does not want to handle the redirect, I should likely ship

lookaside_cgi = https://src.fedoraproject.org/repo/pkgs/upload.cgi

in etc/rpkg/fedpkg.conf.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9980305</commentid>
    <comment_count>1</comment_count>
    <who name="Lubomír Sedlář">lsedlar</who>
    <bug_when>2016-12-13 05:36:17 -0500</bug_when>
    <thetext>Please try with fedpkg-1.26-3 and pyrpkg-1.47-5 from updates-testing.

This is related to using well known SSL certificate:
https://fedoraproject.org/wiki/ReleaseEngineering/FlagDay2016</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9980343</commentid>
    <comment_count>2</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-12-13 05:59:54 -0500</bug_when>
    <thetext>Thanks, that changed the response to

Could not execute new_sources: &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
&lt;html&gt;&lt;head&gt;
&lt;title&gt;401 Unauthorized&lt;/title&gt;
&lt;/head&gt;&lt;body&gt;
&lt;h1&gt;Unauthorized&lt;/h1&gt;
&lt;p&gt;This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn&apos;t understand how to supply
the credentials required.&lt;/p&gt;
&lt;/body&gt;&lt;/html&gt;

which I assume is a good thing.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9980367</commentid>
    <comment_count>3</comment_count>
    <who name="Antonio Trande">anto.trande</who>
    <bug_when>2016-12-13 06:15:47 -0500</bug_when>
    <thetext>Same problem on fedora 25.

Version-Release number of selected component (if applicable):
fedpkg-1.25-1.fc25.noarch</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9980370</commentid>
    <comment_count>4</comment_count>
    <who name="Lubomír Sedlář">lsedlar</who>
    <bug_when>2016-12-13 06:17:08 -0500</bug_when>
    <thetext>That is on it&apos;s way to be a good thing. It means you most likely don&apos;t have a kerberos ticket. It can be obtained by
    kinit &lt;your_fas_login&gt;@FEDORAPROJECT.ORG

Also, to be sure building works correctly, make sure you have koji-1.11.0-1 installed and /etc/koji.conf is up-to-date.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9989290</commentid>
    <comment_count>5</comment_count>
    <who name="Michal Schorm">mschorm</who>
    <bug_when>2016-12-15 06:22:48 -0500</bug_when>
    <thetext>(In reply to Lubomír Sedlář from comment #1)
&gt; Please try with fedpkg-1.26-3 and pyrpkg-1.47-5 from updates-testing.

I encountered the same issue.
I confirm, that I updated those 2 packages and it works fine now.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9990432</commentid>
    <comment_count>6</comment_count>
    <who name="Karel Volný">kvolny</who>
    <bug_when>2016-12-15 10:51:43 -0500</bug_when>
    <thetext>(In reply to Lubomír Sedlář from comment #4)
&gt; That is on it&apos;s way to be a good thing. It means you most likely don&apos;t have
&gt; a kerberos ticket. It can be obtained by
&gt;     kinit &lt;your_fas_login&gt;@FEDORAPROJECT.ORG

hmmmmm ....

$ kinit kvolny@FEDORAPROJECT.ORG
Password for kvolny@FEDORAPROJECT.ORG: 
Password expired.  You must change it now.
Enter new password: 
Enter it again: 
kinit: Cannot find KDC for realm &quot;FEDORAPROJECT.ORG&quot; while getting initial credentials

&gt; Also, to be sure building works correctly, make sure you have koji-1.11.0-1

$ rpm -q koji
koji-1.11.0-1.fc25.noarch

&gt; installed and /etc/koji.conf is up-to-date.

which means ...?

$ stat -c %y /etc/koji.conf
2016-12-09 15:55:40.000000000 +0100

... raising priority/severity, hope someone can resolve this quickly, it blocks me from fixing security vulnerability (arbitrary code execution) :-(</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9990476</commentid>
    <comment_count>7</comment_count>
    <who name="Jan Pazdziora">jpazdziora</who>
    <bug_when>2016-12-15 10:59:24 -0500</bug_when>
    <thetext>Make sure you have

$ rpm -qf /etc/krb5.conf.d/fedoraproject_org 
fedora-packager-0.6.0.0-1.fc25.noarch

Also, check that your /etc/krb5.conf has

includedir /etc/krb5.conf.d/

in it. If you&apos;ve tweaked /etc/krb5.conf, the stock might be in /etc/krb5.conf.rpmnew.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9990579</commentid>
    <comment_count>8</comment_count>
    <who name="Karel Volný">kvolny</who>
    <bug_when>2016-12-15 11:23:35 -0500</bug_when>
    <thetext>(In reply to Jan Pazdziora from comment #7)
&gt; Make sure you have

thanks, but:

&gt; $ rpm -qf /etc/krb5.conf.d/fedoraproject_org 
&gt; fedora-packager-0.6.0.0-1.fc25.noarch

$ rpm -qf /etc/krb5.conf.d/fedoraproject_org
fedora-packager-0.6.0.0-1.fc25.noarch

&gt; Also, check that your /etc/krb5.conf has
&gt; 
&gt; includedir /etc/krb5.conf.d/
&gt; 
&gt; in it. If you&apos;ve tweaked /etc/krb5.conf, the stock might be in
&gt; /etc/krb5.conf.rpmnew.

$ grep includedir /etc/krb5.conf
includedir /etc/krb5.conf.d/

... other suggestions?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9992514</commentid>
    <comment_count>9</comment_count>
    <who name="Lubomír Sedlář">lsedlar</who>
    <bug_when>2016-12-16 03:07:39 -0500</bug_when>
    <thetext>You could try going through Kerberos information from Fedora Infrastructure team.
https://fedoraproject.org/wiki/Infrastructure/Kerberos
This is not a bug in fedpkg, so please follow up on #fedora-infra on IRC or file a ticket at
https://pagure.io/fedora-infrastructure/</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9992534</commentid>
    <comment_count>10</comment_count>
    <who name="Karel Volný">kvolny</who>
    <bug_when>2016-12-16 03:20:58 -0500</bug_when>
    <thetext>sorry, but throwing html source at the user, as described in comment #2, really is not a nice thing to do, no matter what configuration did the user omit</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9992538</commentid>
    <comment_count>11</comment_count>
    <who name="">cqi</who>
    <bug_when>2016-12-16 03:23:16 -0500</bug_when>
    <thetext>Hi Karel, how about use another bug to track this improvement?</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9992547</commentid>
    <comment_count>12</comment_count>
    <who name="Karel Volný">kvolny</who>
    <bug_when>2016-12-16 03:27:28 -0500</bug_when>
    <thetext>why? - look at the description again, this one started exactly with the same problem, fedpkg outputting html source instead of handling that more gracefully</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10171729</commentid>
    <comment_count>13</comment_count>
    <who name="Fedora Admin XMLRPC Client">fedora-admin-xmlrpc</who>
    <bug_when>2017-02-21 11:41:56 -0500</bug_when>
    <thetext>This package has changed ownership in the Fedora Package Database.  Reassigning to the new owner of this component.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10190021</commentid>
    <comment_count>14</comment_count>
    <who name="">cqi</who>
    <bug_when>2017-02-28 03:08:32 -0500</bug_when>
    <thetext>Hi Karel, could you please have a look at the problem you mentioned in comment 12? Currently, fedpkg is able to handle the error and not throw HTML source to user.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10201490</commentid>
    <comment_count>15</comment_count>
    <who name="Karel Volný">kvolny</who>
    <bug_when>2017-03-02 06:48:07 -0500</bug_when>
    <thetext>(In reply to cqi from comment #14)
&gt; Hi Karel, could you please have a look at the problem you mentioned in
&gt; comment 12? Currently, fedpkg is able to handle the error and not throw HTML
&gt; source to user.

well, obviously I cannot reproduce the original problem, however trying new-sources without valid ticket, I&apos;m now getting

Could not execute new_sources: Request is unauthorized.

which looks much better than the output in comment #2, thanks</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10201538</commentid>
    <comment_count>16</comment_count>
    <who name="">cqi</who>
    <bug_when>2017-03-02 07:07:18 -0500</bug_when>
    <thetext>Thanks for you feedback.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>