<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1349721</bug_id>
          
          <creation_ts>2016-06-24 01:33:00 -0400</creation_ts>
          <short_desc>Upgrade from Fedora 24 to Fedora Rawhide with dnf-plugin-system-upgrade fails, system stuck in boot loop until booted with enforcing=0</short_desc>
          <delta_ts>2016-12-12 19:31:51 -0500</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>selinux-policy</component>
          <version>25</version>
          <rep_platform>All</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard>AcceptedBlocker</status_whiteboard>
          <keywords></keywords>
          <priority>urgent</priority>
          <bug_severity>urgent</bug_severity>
          <target_milestone>---</target_milestone>
          
          <blocked>1277287</blocked>
          <everconfirmed>1</everconfirmed>
          <reporter name="Adam Williamson">awilliam</reporter>
          <assigned_to name="Lukas Vrabec">lvrabec</assigned_to>
          <cc>dominick.grift</cc>
    
    
    <cc>dwalsh</cc>
    
    
    <cc>lou</cc>
    
    
    <cc>lvrabec</cc>
    
    
    <cc>mgrepl</cc>
    
    
    <cc>mrsam</cc>
    
    
    <cc>plautrba</cc>
    
    
    <cc>pschindl</cc>
    
    
    <cc>robatino</cc>
    
    
    <cc>zbyszek</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>selinux-policy-3.13.1-208.fc25</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2016-08-16 23:04:37</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9449124</commentid>
    <comment_count>0</comment_count>
    <who name="Adam Williamson">awilliam</who>
    <bug_when>2016-06-24 01:33:00 -0400</bug_when>
    <thetext>To reproduce, just try to upgrade from Fedora 24 to current Rawhide with dnf-plugin-system-upgrade. When you run `dnf system-upgrade reboot`, the system will get stuck in an eternal boot loop - it boots, fails to reach the upgrade target, reboots, tries again, ad infinitum. You can break out by booting with `enforcing=0`, which allows the system to reach the upgrade target and successfully upgrade.

Strangely, this doesn&apos;t seem to affect upgrades from F23 to Rawhide, those work fine.

Proposing as a Beta blocker: &quot;For each one of the release-blocking package sets, it must be possible to successfully complete a direct upgrade from fully updated installations of the last two stable Fedora releases with that package set installed.&quot;

I saw this when upgrading my desktop to Rawhide, openQA is running into it - see https://openqa.fedoraproject.org/tests/23677 , for e.g. - and nivag reported the same thing today in IRC.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9451590</commentid>
    <comment_count>1</comment_count>
    <who name="Adam Williamson">awilliam</who>
    <bug_when>2016-06-24 15:32:49 -0400</bug_when>
    <thetext>So a bit more detail here...to debug this, you can copy /usr/lib/systemd/system/dnf-system-upgrade.service to /etc/systemd/system and drop the FailureAction=reboot line from the copy; this will prevent the system going into a boot loop. You can also do `systemctl enable debug-shell.service` , which gets you a shell on tty9.

Armed with that, and systemd.log_level=debug, I can see this:

dnf-system-upgrade.service: ConditionPathExists=/system-update/.dnf-system-upgrade succeeded.
dnf-system-upgrade.service: Failed to load environment files: Permission denied
dnf-system-upgrade.service: Failed to run &apos;start&apos; task: Permission denied
dnf-system-upgrade.service: Changed dead -&gt; failed
dnf-system-upgrade.service: Job dnf-system-upgrade.service/start finished, result=failed

I can&apos;t find any trace of an AVC, but it&apos;s certainly an SELinux issue, since it works fine with enforcing=0.

/system-updates/.dnf-system-upgrade itself seems to be the &apos;EnvironmentFile&apos; that systemd wants to open - it&apos;s listed as EnvironmentFile in the unit - and its permissions are:

-rw-r--r--. 1 root.root unconfined_u:object_r:rpm_var_lib_t:s0

It would be systemd itself which would try to read the file, I believe, and which is presumably being denied.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9451702</commentid>
    <comment_count>2</comment_count>
    <who name="Adam Williamson">awilliam</who>
    <bug_when>2016-06-24 16:39:40 -0400</bug_when>
    <thetext>I checked the F23 case; /system-update/.dnf-system-upgrade has the exact same permissions and label there, so I guess the difference is that in F23 systemd is permitted to read that file but in F24 it is not...</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9529342</commentid>
    <comment_count>3</comment_count>
    <who name="Zbigniew JÄ™drzejewski-Szmek">zbyszek</who>
    <bug_when>2016-07-19 16:40:55 -0400</bug_when>
    <thetext>I think that the solution is the same as in the (unfinished) .autorelabel discussion: we should boot selinux in permissive mode for the upgrade.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9536047</commentid>
    <comment_count>4</comment_count>
    <who name="Petr Schindler">pschindl</who>
    <bug_when>2016-07-21 05:39:14 -0400</bug_when>
    <thetext>Discussed at 2016-07-20 blocker review meeting: [1]. 

This bug was accepted as Beta blocker: Failing upgrade violates the beta criterion: &quot;For each one of the release-blocking package sets, it must be possible to successfully complete a direct upgrade from fully updated installations of the last two stable Fedora releases with that package set installed.&quot;

[1] https://meetbot.fedoraproject.org/fedora-blocker-review/2016-07-20/f25-blocker-review.2016-07-20-16.00.html</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9537242</commentid>
    <comment_count>5</comment_count>
    <who name="Petr Lautrbach">plautrba</who>
    <bug_when>2016-07-21 10:35:36 -0400</bug_when>
    <thetext>The reason why it fails is that systemd running as init_t tries to read EnvironmentFile - /system-update/.dnf-system-upgrade which is labeled with rpm_var_lib_t type and it&apos;s not allowed in the policy:


# sesearch -A -s init_t -t rpm_var_lib_t 
Found 2 semantic av rules:
   allow init_t file_type : dir { getattr search open } ; 
   allow init_t file_type : filesystem { unmount getattr } ; 


/system-update/ is symlink to /var/lib/dnf/systemd-upgrade which according to matchpathcon has a correct label:

# matchpathcon /var/lib/dnf/systemd-upgrade/.dnf-system-upgrade
/var/lib/dnf/systemd-upgrade/.dnf-system-upgrade	system_u:object_r:rpm_var_lib_t:s0

So the fix could be to add a policy which allows init_t read rpm_var_lib_t.

You can try the following example local policy module:

# cat &gt; localdnfupgradefix.cil &lt;&lt;EOF
(allow init_t rpm_var_lib_t (file (getattr open read)))
EOF
# semodule -i localdnfupgradefix.cil
# dnf system-upgrade reboot</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9537331</commentid>
    <comment_count>6</comment_count>
    <who name="Lukas Vrabec">lvrabec</who>
    <bug_when>2016-07-21 10:53:19 -0400</bug_when>
    <thetext>It make sense. init_t domain was unconfined domain till F23. You can output from F23:
$ sesearch -A -s init_t -t rpm_var_lib_t -c file -p read 
Found 1 semantic av rules:
   allow files_unconfined_type file_type : file { ioctl read write create getattr setattr lock relabelfrom relabelto append unlink link rename execute swapon quotaon mounton execute_no_trans open audit_access } ;


This is reason why it was allowed in &gt;F23. 

From F24, init_t is not unconfined_domain and there is no allow rule for this:

# sesearch -A -s init_t -t rpm_var_lib_t -c file -p read
#

I believe we should add this rule to make it working. 

Petr, 
Thanks for testing.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9549413</commentid>
    <comment_count>7</comment_count>
    <who name="Jan Kurik">jkurik</who>
    <bug_when>2016-07-26 00:37:27 -0400</bug_when>
    <thetext>This bug appears to have been reported against &apos;rawhide&apos; during the Fedora 25 development cycle.
Changing version to &apos;25&apos;.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9611665</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-08-12 11:57:50 -0400</bug_when>
    <thetext>selinux-policy-3.13.1-208.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2016-662487f8f1</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9621005</commentid>
    <comment_count>9</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2016-08-16 23:02:58 -0400</bug_when>
    <thetext>selinux-policy-3.13.1-208.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9925821</commentid>
    <comment_count>10</comment_count>
    <who name="Lou Hafer">lou</who>
    <bug_when>2016-11-24 11:31:57 -0500</bug_when>
    <thetext>It&apos;s still possible to find oneself stuck in this loop using the --datadir option offered by dnf-plugin-system-upgrade. Just upgraded from Fed24 to Fed25 and relocated datadir under /home because it had lots of space. Result was SEL type of home_root_t and failure as described above. The description above is very clear and I was able to use a Fed24 Live CD to boot the system, mount the relevant logical volume, and use chcon to change the SEL type to rpm_var_lib_t. The system upgrade completed with no further issues.

This is a bit of a trap --- there&apos;s no hint that using --datadir will get you this sort of grief. From a user perspective the ideal fix would be for dnf-plugin-system-upgrade to force the SEL context it requires, but this might not be ideal from a security standpoint. Next best would be a warning, something like `You&apos;ve moved the data directory; ensure that the SEL context is rpm_var_lib_t before proceeding with reboot.&apos;</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9978937</commentid>
    <comment_count>11</comment_count>
    <who name="Zbigniew JÄ™drzejewski-Szmek">zbyszek</who>
    <bug_when>2016-12-12 19:31:51 -0500</bug_when>
    <thetext>*** Bug 1398696 has been marked as a duplicate of this bug. ***</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>