<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE bugzilla SYSTEM "https://bugzilla.redhat.com/page.cgi?id=bugzilla.dtd">

<bugzilla version="4.4.12068.1"
          urlbase="https://bugzilla.redhat.com/"
          
          maintainer="bugzilla-error-list@redhat.com"
>

    <bug>
          <bug_id>1399406</bug_id>
          
          <creation_ts>2016-11-28 20:59:00 -0500</creation_ts>
          <short_desc>PSI4 fails to run</short_desc>
          <delta_ts>2017-04-27 16:50:34 -0400</delta_ts>
          <reporter_accessible>1</reporter_accessible>
          <cclist_accessible>1</cclist_accessible>
          <classification_id>2</classification_id>
          <classification>Fedora</classification>
          <product>Fedora</product>
          <component>psi4</component>
          <version>25</version>
          <rep_platform>x86_64</rep_platform>
          <op_sys>Linux</op_sys>
          <bug_status>CLOSED</bug_status>
          <resolution>ERRATA</resolution>
          
          
          <bug_file_loc></bug_file_loc>
          <status_whiteboard></status_whiteboard>
          <keywords></keywords>
          <priority>unspecified</priority>
          <bug_severity>high</bug_severity>
          <target_milestone>---</target_milestone>
          <dependson>1419365</dependson>
          
          <everconfirmed>1</everconfirmed>
          <reporter name="Henrique &quot;LonelySpooky&quot; Junior">henriquecsj</reporter>
          <assigned_to name="Susi Lehtola">susi.lehtola</assigned_to>
          <cc>susi.lehtola</cc>
          <qa_contact name="Fedora Extras Quality Assurance">extras-qa</qa_contact>
          
          <cf_fixed_in>psi4-1.0-2.2118f2fgit.fc25 psi4-1.0-2.2118f2fgit.fc24</cf_fixed_in>
          <cf_doc_type>If docs needed, set a value</cf_doc_type>
          <cf_release_notes></cf_release_notes>
          <cf_story_points>---</cf_story_points>
          
          <cf_environment></cf_environment>
          <cf_last_closed>2017-04-27 01:50:47</cf_last_closed>
          <cf_type>Bug</cf_type>
          <cf_regression_status>---</cf_regression_status>
          <cf_mount_type>---</cf_mount_type>
          <cf_documentation_action>---</cf_documentation_action>
          <cf_crm></cf_crm>
          <cf_verified_branch></cf_verified_branch>
          <cf_category>---</cf_category>
          <cf_ovirt_team>---</cf_ovirt_team>
          
          <cf_cloudforms_team>---</cf_cloudforms_team>
          
          
          
          
          <target_release>---</target_release>
          
          <votes>0</votes>

      

      

      

          <comment_sort_order>oldest_to_newest</comment_sort_order>  
          <long_desc isprivate="0" >
    <commentid>9936960</commentid>
    <comment_count>0</comment_count>
    <who name="Henrique &quot;LonelySpooky&quot; Junior">henriquecsj</who>
    <bug_when>2016-11-28 20:59:43 -0500</bug_when>
    <thetext>Description of problem:
Psi4 crashes immediately when executed.


Version-Release number of selected component (if applicable):
psi4-data-1.0-0.1.rc.15fc63cgit.fc25.noarch
psi4-1.0-0.1.rc.15fc63cgit.fc25.x86_64


How reproducible:
Try to run any simple calculation.


Steps to Reproduce:
1. Create a basic input file:
# Any line starting with the # character is a comment line
#! Sample HF/cc-pVDZ H2O computation

memory 250 mb

molecule h2o {
  O 
  H 1 0.96
  H 1 0.96 2 104.5
}

set basis cc-pVDZ
energy(&apos;scf&apos;)

2. psi4 input.dat

3. crash


Actual results:
Psi4 shows a error message:
An error has occurred python-side. Traceback (most recent call last):

  File &quot;&lt;string&gt;&quot;, line 7, in &lt;module&gt;

  File &quot;/usr/share/psi4/python/driver.py&quot;, line 45, in &lt;module&gt;
    import driver_util

  File &quot;/usr/share/psi4/python/driver_util.py&quot;, line 30, in &lt;module&gt;
    from procedures import *

  File &quot;/usr/share/psi4/python/procedures/__init__.py&quot;, line 1, in &lt;module&gt;
    from proc_table import procedures, hooks, energy_only_methods

  File &quot;/usr/share/psi4/python/procedures/proc_table.py&quot;, line 198, in &lt;module&gt;
    for ssuper in proc.superfunctional_list():

  File &quot;/usr/share/psi4/python/procedures/functional.py&quot;, line 3605, in superfunctional_list
    sup = superfunctionals[key](key, 1, 1)

  File &quot;/usr/share/psi4/python/procedures/functional.py&quot;, line 1953, in build_b3lypd1_superfunctional
    sup = build_b3lyp_superfunctional(name, npoints, deriv)

  File &quot;/usr/share/psi4/python/procedures/functional.py&quot;, line 1224, in build_b3lyp_superfunctional
    sup = psi4.SuperFunctional.blank()

TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr&lt;psi::SuperFunctional&gt;


Expected results:
Quantum chemistry for everyone.

Additional info:</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>9936991</commentid>
    <comment_count>1</comment_count>
    <who name="Susi Lehtola">susi.lehtola</who>
    <bug_when>2016-11-28 21:14:19 -0500</bug_when>
    <thetext>As discussed on https://github.com/psi4/psi4/issues/531, the Boost dependency has been since removed from Psi4. As soon as a new official release is made upstream, I&apos;ll update the packages.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10122289</commentid>
    <comment_count>2</comment_count>
    <who name="Susi Lehtola">susi.lehtola</who>
    <bug_when>2017-02-05 20:41:46 -0500</bug_when>
    <thetext>I&apos;ve ported the spec file to the newest git snapshot. As soon as the dependencies of bug #1419365 are resolved (two packages need to be reviewed), I can update the package in Fedora.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10194111</commentid>
    <comment_count>3</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-28 10:05:21 -0500</bug_when>
    <thetext>pybind11-2.0.1-5.fc25 psi4-1.0-1.926879egit.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-096890604d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10194113</commentid>
    <comment_count>4</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-28 10:05:31 -0500</bug_when>
    <thetext>pybind11-2.0.1-5.fc24 psi4-1.0-1.926879egit.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2017-31ced2cf47</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10195855</commentid>
    <comment_count>5</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-28 21:51:55 -0500</bug_when>
    <thetext>psi4-1.0-1.926879egit.fc24, pybind11-2.0.1-5.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-31ced2cf47</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10195896</commentid>
    <comment_count>6</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-02-28 21:54:55 -0500</bug_when>
    <thetext>psi4-1.0-1.926879egit.fc25, pybind11-2.0.1-5.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-096890604d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10229322</commentid>
    <comment_count>7</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-10 14:05:24 -0500</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc25 pybind11-2.0.1-5.fc25 has been submitted as an update to Fedora 25. https://bodhi.fedoraproject.org/updates/FEDORA-2017-096890604d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10229324</commentid>
    <comment_count>8</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-10 14:05:36 -0500</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc24 pybind11-2.0.1-5.fc24 has been submitted as an update to Fedora 24. https://bodhi.fedoraproject.org/updates/FEDORA-2017-31ced2cf47</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10230345</commentid>
    <comment_count>9</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-11 08:53:17 -0500</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc24, pybind11-2.0.1-5.fc24 has been pushed to the Fedora 24 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-31ced2cf47</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10230384</commentid>
    <comment_count>10</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-03-11 09:24:33 -0500</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc25, pybind11-2.0.1-5.fc25 has been pushed to the Fedora 25 testing repository. If problems still persist, please make note of it in this bug report.
See https://fedoraproject.org/wiki/QA:Updates_Testing for
instructions on how to install test updates.
You can provide feedback for this update here: https://bodhi.fedoraproject.org/updates/FEDORA-2017-096890604d</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10367138</commentid>
    <comment_count>11</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-27 01:50:47 -0400</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc25, pybind11-2.0.1-5.fc25 has been pushed to the Fedora 25 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc><long_desc isprivate="0" >
    <commentid>10370197</commentid>
    <comment_count>12</comment_count>
    <who name="Fedora Update System">updates</who>
    <bug_when>2017-04-27 16:50:34 -0400</bug_when>
    <thetext>psi4-1.0-2.2118f2fgit.fc24, pybind11-2.0.1-5.fc24 has been pushed to the Fedora 24 stable repository. If problems still persist, please make note of it in this bug report.</thetext>
  </long_desc>
      
      

    </bug>

</bugzilla>